name: citus

global:
  crunchyPostgres:
    postgresql:
      parameters:
        max_connections: 200
    storageSize: 10Gi
  crunchyPostgresOperator:
    instances:
      operational:
        name: instance1
        replicas: 1
      analytical:
        name: instance1
        replicas: 1
  imageRegistry: defaultValue
  storageClass: gp2

namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: apps.cicd.mdtu-ddm.projects.epam.com

database:
  required: false
  timezone: UTC

image:
  name: citus-chart
  version: latest

resources:
  requests:
    cpu: 100m
    memory: 1Gi

postgresCluster:
  port: 5432
  postgresVersion: 14
  image:
    name: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis
    version: ubi8-14.3-3.2-0
  pgbackrest:
    image:
      name: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest
      version: ubi8-2.38-1
  pgmonitor:
    podMonitorName: crunchy-postgres-exporter
    exporter:
      image:
        name: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter
        version: ubi8-5.2.0-0
  operationalClusterSecret:
    name: operational-pguser-postgres
  analyticalClusterSecret:
    name: analytical-pguser-postgres
  initContainer:
    image: busybox
  serviceAccountName: citus
  securityContext:
    runAsUser: 999
    fsGroup: 999
  dbName: registry
  archiveSchema: archive
  pubHost: operational-primary
  pubUser: postgres
  pubPort: 5432
  secrets:
    citusSecrets:
      pgsecretName: citus-secrets
      userName: username
      pgsecretKey: password
      rolesSecret: citus-roles-secrets
    citusRolesSecrets:
      anAdm: analytics_admin
      anRole: analytics_auditor
      anSvc: audit_service_user
      settRole: settings_role
      excerptExporter: excerpt_exporter
      excerptSvc: excerpt_service_user
      excerptWork: excerpt_worker_user
      notificationTemplatePublisher: notification_template_publisher_user
      notificationService: notification_service_user
      regOwner: registry_owner_role
      regTemplateOwner: registry_template_owner_role
      appRole: application_role
      admRole: admin_role
      histRole: historical_data_role
      processHistoryRole: process_history_role
      geoserverRole: geoserver_role
  url:
    masterDBurl: jdbc:postgresql://operational-primary:5432
    replicaDBurl: jdbc:postgresql://analytical-primary:5432
  jobName: run-db-scripts-job
  minioSecretName: s3-conf
  region: eu-central-1
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "1"
        repo1-s3-uri-style: path
        repo1-retention-full-type: count
        start-fast: "y"
        repo1-storage-verify-tls: "n"
        repo1-storage-port: "443"
        log-level-file: detail
      repos:
        name: repo1
        schedules:
          full: "0 1 * * *"
  postgresql:
    parameters:
      password_encryption: md5
      log_min_duration_statement: 1000
      log_destination: 'stderr'
      logging_collector: 'off'
      synchronous_standby_names: "*"
