name: citus

global:
  citus:
    masterWorkers: 2
    replicaWorkers: 2
  imageRegistry: defaultValue

namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: apps.cicd.mdtu-ddm.projects.epam.com

database:
  required: false
  timezone: UTC

image:
  name: citus-chart
  version: latest

storageClass: gp2

resources:
  requests:
    cpu: 100m
    memory: 1Gi

citus:
  mastersConfig:
    name: citus-master
    replicaName: citus-master-rep
    replicas: 1
    replicaReplicas: 1
    containers:
      name: citus
      image: citus-data-main:0.1.5-SNAPSHOT.4
      port: 5432
      env:
        pgdata_value: /var/lib/postgresql/data/pgdata
        user_name: username
        pgsecret_name: citus-secrets
        pgsecret_key: password
      volumeMounts:
        name: storage
        mountPath: /var/lib/postgresql/data
    volumes:
      name: storage
      claimName: citus-master-pvc
      replicaClaimName: citus-master-rep-pvc
      size: 5Gi
      replicaSize: 5Gi
  workersConfig:
    name: citus-workers
    replicaName: citus-workers-rep
    containers:
      nodeName: citus-worker
      replicaNodeName: citus-worker-rep
      port: 5432
    volumes:
      name: storage
      size: 5Gi
      replicaSize: 5Gi
  postgresSecret:
    name: citus-secrets
  initContainer:
    image: busybox
  pgpassEnvVariable: /var/lib/postgresql/data/.pgpass
  serviceAccountName: citus
  securityContext:
    runAsUser: 999
    fsGroup: 999
  dbName: registry
  archiveSchema: archive
  pubHost: citus-master
  pubUser: postgres
  pubPort: 5432
  secrets:
    citusSecrets:
      pgsecretName: citus-secrets
      userName: username
      pgsecretKey: password
      rolesSecret: citus-roles-secrets
    citusRolesSecrets:
      anAdm: analytics_admin
      anRole: analytics_auditor
      anSvc: audit_service_user
      settRole: settings_role
      excerptExporter: excerpt_exporter
      excerptSvc: excerpt_service_user
      excerptWork: excerpt_worker_user
      notificationTemplatePublisher: notification_template_publisher_user
      notificationService: notification_service_user
      regOwner: registry_owner_role
      appRole: application_role
      admRole: admin_role
      histRole: historical_data_role
      processHistoryRole: process_history_role
      geoserverRole: geoserver_role
    pgPassConfigMapName: pgpass
  url:
    masterDBurl: jdbc:postgresql://citus-master:5432
    replicaDBurl: jdbc:postgresql://citus-master-rep:5432
  pgConfig:
    name: pg-conf
    mountPath: /etc/postgresql
    configMapName: pgconfig
    logLevel: warning
  jobName: run-db-scripts-job
