apiVersion: v1
kind: Service
metadata:
  name: citus-master
  labels:
    app: citus-master
spec:
  ports:
    - name: operational-pool-port
      protocol: TCP
      port: {{ .Values.postgresCluster.port }}
      targetPort: {{ .Values.postgresCluster.port }}
  selector:
    app: operational-pool
