apiVersion: v1
kind: Service
metadata:
  name: citus-master-rep
  labels:
    app: citus-master-rep
spec:
  selector:
    postgres-operator.crunchydata.com/cluster: analytical
    postgres-operator.crunchydata.com/role: master
  clusterIP: None
  ports:
  - port: 5432
