apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.citus.mastersConfig.name }}
  labels:
    app: {{ .Values.citus.mastersConfig.name }}
spec:
  selector:
    app: {{ .Values.citus.mastersConfig.name }}
  clusterIP: None
  ports:
  - port: {{ .Values.citus.mastersConfig.containers.port }}
