apiVersion: v1
kind: Service
metadata:
  name: citus-master-rep
  labels:
    app: citus-master-rep
spec:
  ports:
  - port: {{ .Values.postgresCluster.port }}
  selector:
    postgres-operator.crunchydata.com/cluster: analytical
