apiVersion: v1
kind: Service
metadata:
  name: citus-master
  labels:
    app: citus-master
spec:
  selector:
    postgres-operator.crunchydata.com/cluster: operational
    postgres-operator.crunchydata.com/role: master
  clusterIP: None
  ports:
  - port: 5432
