kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.citus.mastersConfig.volumes.replicaClaimName }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.citus.mastersConfig.volumes.replicaSize }}
