apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.citus.postgresSecret.name }}
  annotations:
    helm.sh/hook: pre-install
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: {{ randAlphaNum 12 | b64enc | quote }}

